### ISSUE TITLE
Code to register manual setup does not work. 

### ISSUE THREAD

**Issue by prat1800** [PacktPublishing/Microsoft-Dynamics-365-Business-Central-Cookbook#22]
The code source given as an exercise to manual setup does not work and I get the below errors. 

'Record "Business Setup"' does not contain a definition for 'InsertExtensionBusinessSetup'AL(AL0132)

AL0280: The event 'OnRegisterBusinessSetup' is not found in the target.

I am using BC170 on prem. Is there a fix for this?

**Comment by MikeGlue** [comment]
Unfortunately the pattern has changed since I wrote this book. In the base application code, if you look at codeunit 5466 you will see the new pattern. Still straightforward, but you will now have to subscribe to Codeunit 1875 and use the 'OnRegisterManualSetup' event.

From codeunit 5466:


`[EventSubscriber(ObjectType::Codeunit, 1875, 'OnRegisterManualSetup', '', false, false)]`
 `local procedure HandleAPISetup(var Sender: Codeunit "Manual Setup")`
`    var`
`        Info: ModuleInfo;`
`        ManualSetupCategory: Enum "Manual Setup Category";`
`    begin`
`        NavApp.GetCurrentModuleInfo(Info);`
`        Sender.Insert(`
`          BusinessSetupNameTxt, BusinessSetupDescriptionTxt, BusinessSetupKeywordsTxt,`
`          PAGE::"Integration Services Setup", Info.Id(), ManualSetupCategory::Service);`
`    end;`
